"use client";

import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef } from "react";
import { ChartIcon, WalletIcon, MagnifierIcon } from "@/components/Icons";
import roboto from "../../../../assets/roboto.png";

const services = [
  {
    title: "Google Ads Management",
    description: "Strategic campaign management that maximizes ROI through advanced targeting and optimization.",
    icon: <ChartIcon />,
    features: [
      "Search campaigns optimization",
      "Display network advertising",
      "YouTube advertising",
      "Shopping campaigns"
    ]
  },
  {
    title: "Facebook & Instagram Ads",
    description: "Social media advertising that reaches your ideal customers where they spend their time.",
    icon: <WalletIcon />,
    features: [
      "Custom audience creation",
      "Lookalike audience targeting",
      "Creative testing",
      "Cross-platform campaigns"
    ]
  },
  {
    title: "LinkedIn Advertising",
    description: "B2B focused campaigns that connect with decision-makers and generate quality leads.",
    icon: <MagnifierIcon />,
    features: [
      "Sponsored content",
      "Message ads",
      "Lead generation forms",
      "Account-based marketing"
    ]
  },
  {
    title: "Performance Analytics",
    description: "Data-driven insights that continuously improve campaign performance and ROI.",
    icon: <ChartIcon />,
    features: [
      "Conversion tracking",
      "Attribution modeling",
      "Performance reporting",
      "ROI optimization"
    ]
  }
];

const methodologySteps = [
  {
    step: "1",
    title: "Strategic Planning",
    description: "We analyze your business goals, target audience, and competitive landscape to create data-driven strategies."
  },
  {
    step: "2",
    title: "Campaign Setup",
    description: "Implement tracking, create compelling ad creative, and configure campaigns for optimal performance."
  },
  {
    step: "3",
    title: "Launch & Monitor",
    description: "Deploy campaigns across platforms while closely monitoring performance and making real-time adjustments."
  },
  {
    step: "4",
    title: "Optimize & Scale",
    description: "Continuously test and refine campaigns to improve results and scale successful strategies."
  }
];

const campaignTypes = [
  {
    title: "Customer Acquisition",
    description: "Drive new customer growth with targeted campaigns designed to attract and convert your ideal prospects into paying customers.",
    badge: "ACQ",
    color: "from-blue-500 to-blue-700"
  },
  {
    title: "Lead Generation",
    description: "Generate high-quality leads through strategic campaigns that capture interest and nurture prospects through the sales funnel.",
    badge: "LEAD",
    color: "from-green-500 to-green-700"
  },
  {
    title: "Brand Awareness",
    description: "Build brand recognition and reach new audiences with campaigns designed to increase visibility and market presence.",
    badge: "BRAND",
    color: "from-purple-500 to-purple-700"
  },
  {
    title: "Retargeting & Retention",
    description: "Re-engage past visitors and customers with personalized campaigns that drive repeat business and increase lifetime value.",
    badge: "RET",
    color: "from-orange-500 to-orange-700"
  }
];

const performanceMetrics = [
  {
    title: "Return on Ad Spend",
    description: "Track revenue generated for every dollar spent on advertising campaigns.",
    label: "ROAS",
    color: "bg-blue-500"
  },
  {
    title: "Cost Per Acquisition",
    description: "Monitor the cost to acquire each new customer across all channels.",
    label: "CPA",
    color: "bg-green-500"
  },
  {
    title: "Conversion Rate",
    description: "Measure the percentage of visitors who complete desired actions.",
    label: "CVR",
    color: "bg-purple-500"
  },
  {
    title: "Customer Lifetime Value",
    description: "Calculate the total value generated by each customer over time.",
    label: "CLV",
    color: "bg-orange-500"
  }
];

function ProfitablePerformanceMarketing() {
  const sectionRefs = useRef<HTMLElement[]>([]);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) =>
        entries.forEach((entry) => {
          if (entry.isIntersecting) entry.target.classList.add("animate-fade-in");
        }),
      { threshold: 0.1 }
    );
    sectionRefs.current.forEach((r) => r && observer.observe(r));
    return () => sectionRefs.current.forEach((r) => r && observer.unobserve(r));
  }, []);

  const addToRefs = (el: HTMLElement | null) => {
    if (el && !sectionRefs.current.includes(el)) sectionRefs.current.push(el);
  };

  return (
    <>
      <Head>
        <title>Performance Marketing Services | PPC & Paid Advertising by DMiraki</title>
        <meta
          name="description"
          content="Drive profitable growth with DMiraki's performance marketing services. Google Ads, Facebook Ads, and multi-channel campaigns that maximize ROI."
        />
      </Head>

      {/* Animated background blobs */}
      <div className="fixed top-0 left-0 w-full h-full -z-10 overflow-hidden pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-300 rounded-full mix-blend-multiply blur-xl opacity-20 animate-blob animation-delay-2000"></div>
        <div className="absolute top-1/3 right-1/4 w-96 h-96 bg-yellow-300 rounded-full mix-blend-multiply blur-xl opacity-20 animate-blob animation-delay-4000"></div>
        <div className="absolute bottom-1/4 left-1/3 w-96 h-96 bg-pink-300 rounded-full mix-blend-multiply blur-xl opacity-20 animate-blob"></div>
      </div>

      <section className="container pb-24 space-y-12">
        {/* Hero Section */}
        <section
          ref={addToRefs}
          className="relative py-16 lg:py-24 px-4 lg:px-8 bg-gradient-to-br from-blue-50/50 via-white to-purple-50/50 dark:from-gray-900 dark:via-gray-950 dark:to-blue-900/20 transition-opacity duration-1000 opacity-0"
        >
          <div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-8">
              <nav className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                <span>Brand & Reach</span>
                <span>/</span>
                <span className="text-gray-900 dark:text-white">Performance Marketing</span>
              </nav>
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold">
                Profitable Performance{" "}
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">
                  Marketing
                </span>
              </h1>
              <p className="text-xl text-gray-600 dark:text-gray-300">
                Data-Driven Campaigns That Maximize Every Marketing Dollar
              </p>
              <p className="text-lg text-gray-700 dark:text-gray-200">
                Performance marketing isn't about spending more – it's about spending smarter. We combine advanced targeting, compelling creative, and continuous optimization to drive profitable customer acquisition and sustainable growth.
              </p>
              <div className="flex gap-4">
                <button className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white font-semibold py-3 px-8 rounded-full transition-all duration-300 transform hover:-translate-y-1 shadow-lg hover:shadow-xl">
                  Get Campaign Audit
                </button>
                <button className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 hover:border-blue-300 dark:hover:border-blue-700 text-gray-800 dark:text-white font-semibold py-3 px-8 rounded-full transition-all duration-300 transform hover:-translate-y-1 shadow-lg hover:shadow-xl">
                  Schedule Strategy Call
                </button>
              </div>
            </div>
            <div className="relative">
              <div className="absolute -inset-4 bg-gradient-to-r from-blue-400 to-purple-500 rounded-2xl blur-xl opacity-20 animate-pulse"></div>
              <div className="relative rounded-2xl overflow-hidden transform hover:scale-105 transition-transform duration-700">
                <Image
                  src={roboto}
                  alt="Performance Marketing"
                  className="w-full max-w-md mx-auto relative rounded-lg shadow-2xl"
                  width={(roboto as any).width}
                  height={(roboto as any).height}
                  priority
                />
              </div>
            </div>
          </div>
        </section>

        {/* Services Section */}
        <section
          ref={addToRefs}
          className="py-16 lg:py-24 px-4 lg:px-8 bg-white dark:bg-gray-950 transition-opacity duration-1000 opacity-0"
        >
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6">Our Performance Marketing Services</h2>
              <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
                Comprehensive solutions designed to maximize ROI and drive measurable results.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
              {services.map((service, index) => (
                <div
                  key={service.title}
                  className="bg-gradient-to-br from-gray-50 to-white dark:from-gray-900 dark:to-gray-800 p-8 rounded-2xl border border-gray-200 dark:border-gray-800 shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-2"
                >
                  <div className="w-14 h-14 rounded-xl bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center mb-6 text-blue-600 dark:text-blue-400">
                    {service.icon}
                  </div>
                  <h3 className="text-xl font-semibold mb-4">{service.title}</h3>
                  <p className="text-gray-600 dark:text-gray-300 mb-4">{service.description}</p>
                  <ul className="space-y-2">
                    {service.features.map((feature, idx) => (
                      <li key={idx} className="flex items-start gap-2 text-sm">
                        <span className="inline-block w-2 h-2 rounded-full bg-blue-500 mt-1.5 flex-shrink-0"></span>
                        <span className="text-gray-700 dark:text-gray-200">{feature}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Methodology Section */}
        <section
          ref={addToRefs}
          className="py-16 lg:py-24 px-4 lg:px-8 bg-gradient-to-br from-blue-50/80 via-white to-purple-50/80 dark:from-gray-900 dark:via-gray-950 dark:to-blue-900/40 transition-opacity duration-1000 opacity-0"
        >
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6">Our Performance Marketing Methodology</h2>
              <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
                A proven framework that delivers measurable business outcomes.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
              {methodologySteps.map((step, index) => (
                <div
                  key={step.step}
                  className="relative bg-gradient-to-br from-gray-50 to-white dark:from-gray-900 dark:to-gray-800 p-8 rounded-2xl border border-gray-200 dark:border-gray-800 shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-2"
                >
                  <div className="absolute -top-4 -left-4 w-10 h-10 rounded-full bg-blue-600 text-white font-bold flex items-center justify-center">
                    {step.step}
                  </div>
                  <h3 className="text-lg font-semibold mb-2 mt-4">{step.title}</h3>
                  <p className="text-gray-600 dark:text-gray-300">{step.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Campaign Types Section */}
        <section
          ref={addToRefs}
          className="py-16 lg:py-24 px-4 lg:px-8 bg-white dark:bg-gray-950 transition-opacity duration-1000 opacity-0"
        >
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6">Campaign Types We Excel At</h2>
              <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
                Tailored strategies to match business goals and lifecycle.
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-8">
              {campaignTypes.map((campaign, index) => (
                <div
                  key={campaign.title}
                  className={`bg-gradient-to-r ${campaign.color} text-white rounded-2xl p-8 shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-2`}
                >
                  <div className="w-16 h-16 bg-white/20 rounded-full flex items-center justify-center mb-6">
                    <span className="text-2xl font-bold">{campaign.badge}</span>
                  </div>
                  <h3 className="text-2xl font-bold mb-3">{campaign.title}</h3>
                  <p className="text-white/85">{campaign.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Performance Metrics Section */}
        <section
          ref={addToRefs}
          className="py-16 lg:py-24 px-4 lg:px-8 bg-gradient-to-br from-gray-900 to-blue-900 text-white transition-opacity duration-1000 opacity-0"
        >
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6">Performance Metrics We Deliver</h2>
              <p className="text-xl text-white/80 max-w-3xl mx-auto">
                Data-driven insights that continuously improve performance.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
              {performanceMetrics.map((metric, index) => (
                <div
                  key={metric.title}
                  className="text-center bg-white/5 backdrop-blur-sm p-8 rounded-2xl hover:bg-white/10 transition-all duration-300 hover:-translate-y-2"
                >
                  <div className={`w-20 h-20 ${metric.color} rounded-full flex items-center justify-center mx-auto mb-6 text-2xl font-bold`}>
                    {metric.label}
                  </div>
                  <h3 className="text-xl font-semibold mb-3">{metric.title}</h3>
                  <p className="text-white/80">{metric.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        <style jsx>{`
          @keyframes blob {
            0% { transform: translate(0px, 0px) scale(1); }
            33% { transform: translate(30px, -50px) scale(1.1); }
            66% { transform: translate(-20px, 20px) scale(0.9); }
            100% { transform: translate(0px, 0px) scale(1); }
          }
          .animate-blob { animation: blob 7s infinite; }
          .animation-delay-2000 { animation-delay: 2s; }
          .animation-delay-4000 { animation-delay: 4s; }
          .animate-fade-in { opacity: 1 !important; }
        `}</style>
      </section>
    </>
  );
}

export default ProfitablePerformanceMarketing;