"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef } from "react";
import { ChartIcon, WalletIcon, MagnifierIcon } from "@/components/Icons";
import roboto from "../../../../assets/roboto.png";

const services = [
  {
    title: "Google Ads Management",
    description: "Strategic Google Ads management that maximizes ROI through advanced targeting and optimization for lead generation advertising.",
    icon: <ChartIcon />,
    features: [
      "Search campaigns optimization",
      "Display network advertising",
      "YouTube advertising",
      "Shopping campaigns"
    ]
  },
  {
    title: "Facebook & Instagram Ads",
    description: "Paid social media advertising that reaches your ideal customers where they spend their time with high-intent targeting.",
    icon: <WalletIcon />,
    features: [
      "Custom audience creation",
      "Lookalike audience targeting",
      "Creative testing",
      "Cross-platform campaigns"
    ]
  },
  {
    title: "LinkedIn Advertising",
    description: "B2B focused campaigns that connect with decision-makers and generate quality leads through performance-based marketing strategies.",
    icon: <MagnifierIcon />,
    features: [
      "Sponsored content",
      "Message ads",
      "Lead generation forms",
      "Account-based marketing"
    ]
  },
  {
    title: "Performance Analytics",
    description: "Data-driven insights that continuously improve campaign performance and ROI. Our performance analytics help you maximize advertising ROI.",
    icon: <ChartIcon />,
    features: [
      "Conversion tracking",
      "Attribution modeling",
      "Performance reporting",
      "ROI optimization"
    ]
  }
];

const methodologySteps = [
  {
    step: "1",
    title: "Strategic Planning",
    description: "We analyze your business goals, target audience, and competitive landscape to create data-driven strategies."
  },
  {
    step: "2",
    title: "Campaign Setup",
    description: "Implement tracking, create compelling ad creative, and configure campaigns for optimal performance."
  },
  {
    step: "3",
    title: "Launch & Monitor",
    description: "Deploy campaigns across platforms while closely monitoring performance and making real-time adjustments."
  },
  {
    step: "4",
    title: "Optimize & Scale",
    description: "Continuously test and refine campaigns to improve results and scale successful strategies."
  }
];

const campaignTypes = [
  {
    title: "Customer Acquisition",
    description: "Drive new customer growth with targeted campaigns designed to attract and convert your ideal prospects into paying customers. Our lead generation advertising strategies ensure maximum customer acquisition ROI.",
    badge: "ACQ",
    color: "from-blue-500 to-blue-700"
  },
  {
    title: "Lead Generation",
    description: "Generate high-quality leads through strategic campaigns that capture interest and nurture prospects through the sales funnel. Our data-driven marketing campaigns focus on scalable lead generation.",
    badge: "LEAD",
    color: "from-green-500 to-green-700"
  },
  {
    title: "Brand Awareness",
    description: "Build brand recognition and reach new audiences with campaigns designed to increase visibility and market presence. Our performance-based marketing agency approach ensures brand awareness that converts.",
    badge: "BRAND",
    color: "from-purple-500 to-purple-700"
  },
  {
    title: "Retargeting & Retention",
    description: "Re-engage past visitors and customers with personalized campaigns that drive repeat business and increase lifetime value. Our scalable PPC campaigns optimize for customer retention.",
    badge: "RET",
    color: "from-orange-500 to-orange-700"
  }
];

const performanceMetrics = [
  {
    title: "Return on Ad Spend",
    description: "Track revenue generated for every dollar spent on advertising campaigns. Our ROI marketing strategies maximize your return on ad spend.",
    label: "ROAS",
    color: "bg-blue-500"
  },
  {
    title: "Cost Per Acquisition",
    description: "Monitor the cost to acquire each new customer across all channels. Our performance marketing approach reduces cost per acquisition while increasing quality.",
    label: "CPA",
    color: "bg-green-500"
  },
  {
    title: "Conversion Rate",
    description: "Measure the percentage of visitors who complete desired actions. Our data-driven marketing campaigns optimize for higher conversion rates.",
    label: "CVR",
    color: "bg-purple-500"
  },
  {
    title: "Customer Lifetime Value",
    description: "Calculate the total value generated by each customer over time. Our scalable PPC campaigns focus on maximizing customer lifetime value.",
    label: "CLV",
    color: "bg-orange-500"
  }
];

export default function ProfitablePerformanceMarketingClient() {
  const sectionRefs = useRef<HTMLElement[]>([]);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) =>
        entries.forEach((entry) => {
          if (entry.isIntersecting) entry.target.classList.add("animate-fade-in");
        }),
      { threshold: 0.1 }
    );
    sectionRefs.current.forEach((r) => r && observer.observe(r));
    return () => sectionRefs.current.forEach((r) => r && observer.unobserve(r));
  }, []);

  const addToRefs = (el: HTMLElement | null) => {
    if (el && !sectionRefs.current.includes(el)) sectionRefs.current.push(el);
  };

  return (
    <>
      {/* Animated background blobs */}
      <div className="fixed top-0 left-0 w-full h-full -z-10 overflow-hidden pointer-events-none">
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-300 rounded-full mix-blend-multiply blur-xl opacity-20 animate-blob animation-delay-2000"></div>
        <div className="absolute top-1/3 right-1/4 w-96 h-96 bg-yellow-300 rounded-full mix-blend-multiply blur-xl opacity-20 animate-blob animation-delay-4000"></div>
        <div className="absolute bottom-1/4 left-1/3 w-96 h-96 bg-pink-300 rounded-full mix-blend-multiply blur-xl opacity-20 animate-blob"></div>
      </div>

      <section className="container pb-24 space-y-12">
        {/* Hero Section */}
        <section
          ref={addToRefs}
          className="relative py-16 lg:py-24 px-4 lg:px-8 bg-gradient-to-br from-blue-50/50 via-white to-purple-50/50 dark:from-gray-900 dark:via-gray-950 dark:to-blue-900/20 transition-opacity duration-1000 opacity-0"
        >
          <div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-8">
              <nav className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                <span>Brand & Reach</span>
                <span>/</span>
                <span className="text-gray-900 dark:text-white">Performance Marketing</span>
              </nav>
              <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold">
                Profitable Performance{" "}
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">
                  Marketing
                </span>
              </h1>
              <p className="text-xl text-gray-600 dark:text-gray-300">
                Data-Driven Campaigns That Maximize Every Marketing Dollar
              </p>
              <p className="text-lg text-gray-700 dark:text-gray-200">
                Performance marketing isn't about spending more – it's about spending smarter. Our data-driven marketing campaigns combine advanced targeting, compelling creative, and continuous optimization to drive profitable customer acquisition and sustainable growth. With our scalable PPC campaigns and performance-based marketing approach, we help you maximize advertising ROI while reducing costs.
              </p>
              <div className="flex gap-4">
                <button className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-600 text-white font-semibold py-3 px-8 rounded-full transition-all duration-300 transform hover:-translate-y-1 shadow-lg hover:shadow-xl">
                  Get Campaign Audit
                </button>
                <button className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 hover:border-blue-300 dark:hover:border-blue-700 text-gray-800 dark:text-white font-semibold py-3 px-8 rounded-full transition-all duration-300 transform hover:-translate-y-1 shadow-lg hover:shadow-xl">
                  Schedule Strategy Call
                </button>
              </div>
            </div>
            <div className="relative">
              <div className="absolute -inset-4 bg-gradient-to-r from-blue-400 to-purple-500 rounded-2xl blur-xl opacity-20 animate-pulse"></div>
              <div className="relative rounded-2xl overflow-hidden transform hover:scale-105 transition-transform duration-700">
                <Image
                  src={roboto}
                  alt="Performance Marketing"
                  className="w-full max-w-md mx-auto relative rounded-lg shadow-2xl"
                  width={roboto.width}
                  height={roboto.height}
                  priority
                />
              </div>
            </div>
          </div>
        </section>

        {/* Services Section */}
        <section
          ref={addToRefs}
          className="py-16 lg:py-24 px-4 lg:px-8 bg-white dark:bg-gray-950 transition-opacity duration-1000 opacity-0"
        >
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6">
                Our Performance <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">Marketing Services</span>
              </h2>
              <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
                Comprehensive solutions designed to maximize your advertising ROI and drive measurable business results.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
              {services.map((service, index) => (
                <div
                  key={index}
                  className="bg-gradient-to-br from-gray-50 to-white dark:from-gray-900 dark:to-gray-800 p-8 rounded-2xl border border-gray-200 dark:border-gray-800 shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-2"
                >
                  <div className="w-12 h-12 rounded-full bg-gradient-to-r from-blue-500 to-purple-500 flex items-center justify-center text-white mb-6">
                    {service.icon}
                  </div>
                  <h3 className="text-xl font-semibold mb-4">{service.title}</h3>
                  <p className="text-gray-600 dark:text-gray-300 mb-6">{service.description}</p>
                  <ul className="space-y-2">
                    {service.features.map((feature, idx) => (
                      <li key={idx} className="flex items-center text-gray-600 dark:text-gray-300">
                        <div className="w-2 h-2 rounded-full bg-gradient-to-r from-blue-500 to-purple-500 mr-3"></div>
                        {feature}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Methodology */}
        <section
          ref={addToRefs}
          className="py-16 lg:py-24 px-4 lg:px-8 bg-gradient-to-br from-blue-50/80 via-white to-purple-50/80 dark:from-gray-900 dark:via-gray-950 dark:to-blue-900/40 transition-opacity duration-1000 opacity-0"
        >
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6">
                Our <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">Methodology</span>
              </h2>
              <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
                A proven 4-step approach that ensures consistent results and maximized ROI.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
              {methodologySteps.map((step, index) => (
                <div
                  key={index}
                  className="relative bg-gradient-to-br from-gray-50 to-white dark:from-gray-900 dark:to-gray-800 p-8 rounded-2xl border border-gray-200 dark:border-gray-800 shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-2"
                >
                  <div className="absolute -top-4 -left-4 w-12 h-12 rounded-full bg-gradient-to-r from-blue-500 to-purple-500 flex items-center justify-center text-white font-bold text-xl">
                    {step.step}
                  </div>
                  <h3 className="text-xl font-semibold mb-4 mt-4">{step.title}</h3>
                  <p className="text-gray-600 dark:text-gray-300">{step.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Campaign Types */}
        <section
          ref={addToRefs}
          className="py-16 lg:py-24 px-4 lg:px-8 bg-white dark:bg-gray-950 transition-opacity duration-1000 opacity-0"
        >
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6">
                Campaign <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">Types</span>
              </h2>
              <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
                Specialized strategies for different business objectives and growth stages.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
              {campaignTypes.map((campaign, index) => (
                <div
                  key={index}
                  className="bg-gradient-to-br from-gray-50 to-white dark:from-gray-900 dark:to-gray-800 p-8 rounded-2xl border border-gray-200 dark:border-gray-800 shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-2"
                >
                  <div className={`inline-block px-3 py-1 rounded-full text-white font-bold mb-4 bg-gradient-to-r ${campaign.color}`}>
                    {campaign.badge}
                  </div>
                  <h3 className="text-xl font-semibold mb-4">{campaign.title}</h3>
                  <p className="text-gray-600 dark:text-gray-300">{campaign.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Performance Metrics */}
        <section
          ref={addToRefs}
          className="py-16 lg:py-24 px-4 lg:px-8 bg-gradient-to-br from-blue-50/80 via-white to-purple-50/80 dark:from-gray-900 dark:via-gray-950 dark:to-blue-900/40 transition-opacity duration-1000 opacity-0"
        >
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold mb-6">
                Key Performance <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">Metrics</span>
              </h2>
              <p className="text-xl text-gray-600 dark:text-gray-300 max-w-3xl mx-auto">
                The metrics we track and optimize to ensure maximum campaign effectiveness.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
              {performanceMetrics.map((metric, index) => (
                <div
                  key={index}
                  className="bg-gradient-to-br from-gray-50 to-white dark:from-gray-900 dark:to-gray-800 p-8 rounded-2xl border border-gray-200 dark:border-gray-800 shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-2"
                >
                  <div className={`${metric.color} w-16 h-16 rounded-full flex items-center justify-center text-white font-bold text-xl mb-6 mx-auto`}>
                    {metric.label}
                  </div>
                  <h3 className="text-xl font-semibold mb-4 text-center">{metric.title}</h3>
                  <p className="text-gray-600 dark:text-gray-300 text-center">{metric.description}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-16 lg:py-24 px-4 lg:px-8 bg-white dark:bg-gray-950">
          <div className="max-w-4xl mx-auto text-center bg-gradient-to-r from-blue-50 to-purple-50 dark:from-gray-900 dark:to-gray-800 p-12 rounded-3xl border border-gray-200 dark:border-gray-800 shadow-xl">
            <h2 className="text-3xl md:text-4xl font-bold mb-6">
              Ready to Maximize Your Marketing ROI?
            </h2>
            <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
              Let's build performance-driven campaigns that deliver measurable results.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/contact-us" className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-600 text-white font-semibold py-4 px-8 rounded-full transition-all duration-300 transform hover:-translate-y-1 shadow-lg hover:shadow-xl">
                Schedule a Consultation
              </Link>
              <Link href="/blogs" className="bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-700 hover:border-blue-300 dark:hover:border-blue-700 text-gray-800 dark:text-white font-semibold py-4 px-8 rounded-full transition-all duration-300 transform hover:-translate-y-1 shadow-lg hover:shadow-xl">
                View Case Studies
              </Link>
            </div>
          </div>
        </section>

        <style jsx>{`
          @keyframes blob {
            0% { transform: translate(0px, 0px) scale(1); }
            33% { transform: translate(30px, -50px) scale(1.1); }
            66% { transform: translate(-20px, 20px) scale(0.9); }
            100% { transform: translate(0px, 0px) scale(1); }
          }
          .animate-blob { animation: blob 7s infinite; }
          .animation-delay-2000 { animation-delay: 2s; }
          .animation-delay-4000 { animation-delay: 4s; }
          .animate-fade-in { opacity: 1 !important; }
        `}</style>
      </section>
    </>
  );
}